





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using System.ComponentModel;
using System.Xml.Serialization;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Converters;


namespace Slack
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }
		
		[SitecoreInfo(SitecoreInfoType.TemplateName)]
		string TemplateName { get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		[IndexField("_id")]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
		[IndexField("_language")]
        public virtual Language Language{ get; private set; }

		[TypeConverter(typeof(IndexFieldItemUriValueConverter))]
        [XmlIgnore]
        [IndexField("_uniqueid")]
        public virtual ItemUri Uri { get; set; }
		
		[SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version
        {
            get
            {
                return Uri == null ? 0 : Uri.Version.Number;
            }
        }

		[SitecoreInfo(SitecoreInfoType.Name)]
		public virtual string ItemName { get; set; }
		
		[SitecoreInfo(SitecoreInfoType.TemplateName)]
		public virtual string TemplateName { get; private set; }
		
		[SitecoreInfo(SitecoreInfoType.DisplayName)]
		public virtual string ItemDisplayName { get; set; }

		[SitecoreParent]
        public virtual IGlassBase ParentBase { get; set; }

		[SitecoreField("__created")]
		public virtual DateTime Created { get; private set; }

		[SitecoreField("__updated")]
		public virtual DateTime Updated { get; private set; }

		[SitecoreField("__Updated by")]
		public virtual string UpdatedBy { get; set; }

	}
}
namespace Slack
{


 	/// <summary>
	/// IChannel Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Channel</para>	
	/// <para>ID: 0127cf54-20a6-4df2-9a5d-95a84e209c22</para>	
	/// </summary>
	[SitecoreType(TemplateId=Channel.TemplateIdString, AutoMap=true)]
	public partial interface IChannel : IGlassBase 
	{
		/// <summary>
		/// The Channel Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: e8dac703-95e6-4cac-85ec-efe4c9f6438c</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Channel.Channel_NameFieldName)]
		string Channel_Name  {get; set;}
			
		/// <summary>
		/// The Description field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 668e7112-b7a9-4bed-93c2-9421aa77b5e8</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Channel.DescriptionFieldName)]
		string Description  {get; set;}
			
	}

	
	/// <summary>
	/// Channel
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Channel</para>	
	/// <para>ID: 0127cf54-20a6-4df2-9a5d-95a84e209c22</para>	
	/// </summary>
	[SitecoreType(TemplateId=Channel.TemplateIdString, AutoMap=true)]
	public partial class Channel  : GlassBase, IChannel 
	{
	    
		public const string TemplateIdString = "0127cf54-20a6-4df2-9a5d-95a84e209c22";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateNameStatic = "Channel";

		/// <summary>
		/// The Channel Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: e8dac703-95e6-4cac-85ec-efe4c9f6438c</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Channel.Channel_NameFieldName)]
		public virtual string Channel_Name  {get; set;}

		public static readonly ID Channel_NameFieldId = new ID("e8dac703-95e6-4cac-85ec-efe4c9f6438c");
		public const string Channel_NameFieldName = "Channel Name";
			
		/// <summary>
		/// The Description field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 668e7112-b7a9-4bed-93c2-9421aa77b5e8</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Channel.DescriptionFieldName)]
		public virtual string Description  {get; set;}

		public static readonly ID DescriptionFieldId = new ID("668e7112-b7a9-4bed-93c2-9421aa77b5e8");
		public const string DescriptionFieldName = "Description";
			
	
	}
}
namespace Slack
{


 	/// <summary>
	/// IEvent_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Event Folder</para>	
	/// <para>ID: 2bfc1077-8359-401f-84d4-5b34d3cf2889</para>	
	/// </summary>
	[SitecoreType(TemplateId=Event_Folder.TemplateIdString, AutoMap=true)]
	public partial interface IEvent_Folder : IGlassBase 
	{
	}

	
	/// <summary>
	/// Event_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Event Folder</para>	
	/// <para>ID: 2bfc1077-8359-401f-84d4-5b34d3cf2889</para>	
	/// </summary>
	[SitecoreType(TemplateId=Event_Folder.TemplateIdString, AutoMap=true)]
	public partial class Event_Folder  : GlassBase, IEvent_Folder 
	{
	    
		public const string TemplateIdString = "2bfc1077-8359-401f-84d4-5b34d3cf2889";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateNameStatic = "Event Folder";

	
	}
}
namespace Slack
{


 	/// <summary>
	/// ITeam_Context Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Team Context</para>	
	/// <para>ID: 457d4151-335d-4828-921f-a7e1b0a722e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=Team_Context.TemplateIdString, AutoMap=true)]
	public partial interface ITeam_Context : IGlassBase 
	{
		/// <summary>
		/// The token field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 9c06739f-1865-472b-9c65-60da4a83927a</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Team_Context.TokenFieldName)]
		string Token  {get; set;}
			
		/// <summary>
		/// The username field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: dd3dfde6-4199-4f94-a76e-14642f98c5de</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Team_Context.UsernameFieldName)]
		string Username  {get; set;}
			
	}

	
	/// <summary>
	/// Team_Context
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Team Context</para>	
	/// <para>ID: 457d4151-335d-4828-921f-a7e1b0a722e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=Team_Context.TemplateIdString, AutoMap=true)]
	public partial class Team_Context  : GlassBase, ITeam_Context 
	{
	    
		public const string TemplateIdString = "457d4151-335d-4828-921f-a7e1b0a722e1";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateNameStatic = "Team Context";

		/// <summary>
		/// The token field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 9c06739f-1865-472b-9c65-60da4a83927a</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Team_Context.TokenFieldName)]
		public virtual string Token  {get; set;}

		public static readonly ID TokenFieldId = new ID("9c06739f-1865-472b-9c65-60da4a83927a");
		public const string TokenFieldName = "token";
			
		/// <summary>
		/// The username field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: dd3dfde6-4199-4f94-a76e-14642f98c5de</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Team_Context.UsernameFieldName)]
		public virtual string Username  {get; set;}

		public static readonly ID UsernameFieldId = new ID("dd3dfde6-4199-4f94-a76e-14642f98c5de");
		public const string UsernameFieldName = "username";
			
	
	}
}
namespace Slack
{


 	/// <summary>
	/// IPublication_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Publication Folder</para>	
	/// <para>ID: dc193d8e-2850-4bd9-aba8-f4afe43cfe7e</para>	
	/// </summary>
	[SitecoreType(TemplateId=Publication_Folder.TemplateIdString, AutoMap=true)]
	public partial interface IPublication_Folder : IGlassBase 
	{
	}

	
	/// <summary>
	/// Publication_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Publication Folder</para>	
	/// <para>ID: dc193d8e-2850-4bd9-aba8-f4afe43cfe7e</para>	
	/// </summary>
	[SitecoreType(TemplateId=Publication_Folder.TemplateIdString, AutoMap=true)]
	public partial class Publication_Folder  : GlassBase, IPublication_Folder 
	{
	    
		public const string TemplateIdString = "dc193d8e-2850-4bd9-aba8-f4afe43cfe7e";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateNameStatic = "Publication Folder";

	
	}
}
namespace Slack
{


 	/// <summary>
	/// IEvent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Event</para>	
	/// <para>ID: e8a6891d-ce13-4e9a-a002-d98fee6dec96</para>	
	/// </summary>
	[SitecoreType(TemplateId=Event.TemplateIdString, AutoMap=true)]
	public partial interface IEvent : IGlassBase 
	{
		/// <summary>
		/// The Description field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 3c5a56da-ac04-48e2-b465-b0b6fc867caf</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Event.DescriptionFieldName)]
		string Description  {get; set;}
			
		/// <summary>
		/// The Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f7ec9e45-42fd-4d18-a259-3b8013cf298b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Event.NameFieldName)]
		string Name  {get; set;}
			
	}

	
	/// <summary>
	/// Event
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Event</para>	
	/// <para>ID: e8a6891d-ce13-4e9a-a002-d98fee6dec96</para>	
	/// </summary>
	[SitecoreType(TemplateId=Event.TemplateIdString, AutoMap=true)]
	public partial class Event  : GlassBase, IEvent 
	{
	    
		public const string TemplateIdString = "e8a6891d-ce13-4e9a-a002-d98fee6dec96";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateNameStatic = "Event";

		/// <summary>
		/// The Description field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 3c5a56da-ac04-48e2-b465-b0b6fc867caf</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Event.DescriptionFieldName)]
		public virtual string Description  {get; set;}

		public static readonly ID DescriptionFieldId = new ID("3c5a56da-ac04-48e2-b465-b0b6fc867caf");
		public const string DescriptionFieldName = "Description";
			
		/// <summary>
		/// The Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f7ec9e45-42fd-4d18-a259-3b8013cf298b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Event.NameFieldName)]
		public virtual string Name  {get; set;}

		public static readonly ID NameFieldId = new ID("f7ec9e45-42fd-4d18-a259-3b8013cf298b");
		public const string NameFieldName = "Name";
			
	
	}
}
namespace Slack
{


 	/// <summary>
	/// IPublication Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Publication</para>	
	/// <para>ID: e8bd1697-9a84-4d18-91d1-4fc9f8594b6e</para>	
	/// </summary>
	[SitecoreType(TemplateId=Publication.TemplateIdString, AutoMap=true)]
	public partial interface IPublication : IGlassBase 
	{
		/// <summary>
		/// The Description field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 9432b5e6-1ddb-41e7-b4d3-5fcf9b63f6bd</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Publication.DescriptionFieldName)]
		string Description  {get; set;}
			
		/// <summary>
		/// The Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ad560039-1bab-4136-bb25-597e5c706c39</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Publication.NameFieldName)]
		string Name  {get; set;}
			
		/// <summary>
		/// The Channels field.
		/// <para></para>
		/// <para>Field Type: Treelist</para>		
		/// <para>Field ID: 99ab54d0-2d15-4654-84c4-3aa806e5dc7b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Publication.ChannelsFieldName)]
		IEnumerable<Guid> Channels  {get; set;}
			
		/// <summary>
		/// The Events field.
		/// <para></para>
		/// <para>Field Type: Treelist</para>		
		/// <para>Field ID: dbb566a8-2404-4fea-95d3-3ab7f91b3c49</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Publication.EventsFieldName)]
		IEnumerable<Guid> Events  {get; set;}
			
		/// <summary>
		/// The Message field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 013a8d98-6aa7-4bd9-80b4-4558ca34d563</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Publication.MessageFieldName)]
		string Message  {get; set;}
			
		/// <summary>
		/// The TeamContext field.
		/// <para></para>
		/// <para>Field Type: Droptree</para>		
		/// <para>Field ID: 4ec68282-940e-4996-8e5d-05ceae67f009</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Publication.TeamContextFieldName)]
		Guid TeamContext  {get; set;}
			
	}

	
	/// <summary>
	/// Publication
	/// <para></para>
	/// <para>Path: /sitecore/templates/Slack/Publication</para>	
	/// <para>ID: e8bd1697-9a84-4d18-91d1-4fc9f8594b6e</para>	
	/// </summary>
	[SitecoreType(TemplateId=Publication.TemplateIdString, AutoMap=true)]
	public partial class Publication  : GlassBase, IPublication 
	{
	    
		public const string TemplateIdString = "e8bd1697-9a84-4d18-91d1-4fc9f8594b6e";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateNameStatic = "Publication";

		/// <summary>
		/// The Description field.
		/// <para></para>
		/// <para>Field Type: Multi-Line Text</para>		
		/// <para>Field ID: 9432b5e6-1ddb-41e7-b4d3-5fcf9b63f6bd</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Publication.DescriptionFieldName)]
		public virtual string Description  {get; set;}

		public static readonly ID DescriptionFieldId = new ID("9432b5e6-1ddb-41e7-b4d3-5fcf9b63f6bd");
		public const string DescriptionFieldName = "Description";
			
		/// <summary>
		/// The Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ad560039-1bab-4136-bb25-597e5c706c39</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Publication.NameFieldName)]
		public virtual string Name  {get; set;}

		public static readonly ID NameFieldId = new ID("ad560039-1bab-4136-bb25-597e5c706c39");
		public const string NameFieldName = "Name";
			
		/// <summary>
		/// The Channels field.
		/// <para></para>
		/// <para>Field Type: Treelist</para>		
		/// <para>Field ID: 99ab54d0-2d15-4654-84c4-3aa806e5dc7b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Publication.ChannelsFieldName)]
		public virtual IEnumerable<Guid> Channels  {get; set;}

		public static readonly ID ChannelsFieldId = new ID("99ab54d0-2d15-4654-84c4-3aa806e5dc7b");
		public const string ChannelsFieldName = "Channels";
			
		/// <summary>
		/// The Events field.
		/// <para></para>
		/// <para>Field Type: Treelist</para>		
		/// <para>Field ID: dbb566a8-2404-4fea-95d3-3ab7f91b3c49</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Publication.EventsFieldName)]
		public virtual IEnumerable<Guid> Events  {get; set;}

		public static readonly ID EventsFieldId = new ID("dbb566a8-2404-4fea-95d3-3ab7f91b3c49");
		public const string EventsFieldName = "Events";
			
		/// <summary>
		/// The Message field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 013a8d98-6aa7-4bd9-80b4-4558ca34d563</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Publication.MessageFieldName)]
		public virtual string Message  {get; set;}

		public static readonly ID MessageFieldId = new ID("013a8d98-6aa7-4bd9-80b4-4558ca34d563");
		public const string MessageFieldName = "Message";
			
		/// <summary>
		/// The TeamContext field.
		/// <para></para>
		/// <para>Field Type: Droptree</para>		
		/// <para>Field ID: 4ec68282-940e-4996-8e5d-05ceae67f009</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Publication.TeamContextFieldName)]
		public virtual Guid TeamContext  {get; set;}

		public static readonly ID TeamContextFieldId = new ID("4ec68282-940e-4996-8e5d-05ceae67f009");
		public const string TeamContextFieldName = "TeamContext";
			
	
	}
}
